/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniDemo */

#ifndef _Included_jni_JniDemo
#define _Included_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniDemo
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JniDemo_helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
